# need to find a better one
cssPath = (el) ->
  if !(el instanceof Element)
    return
  path = []
  while el.nodeType == Node.ELEMENT_NODE
    selector = el.nodeName.toLowerCase()
    if el.id
      selector += '#' + el.id
      path.unshift selector
      break
    else
      sib = el
      nth = 1
      while sib = sib.previousElementSibling
        if sib.nodeName.toLowerCase() == selector
          nth++
      if nth != 1
        selector += ':nth-of-type(' + nth + ')'
    path.unshift selector
    el = el.parentNode
  path.join ' > '

getFunc = (word, prefix)=>
  if prefix is 'lower_case'
    func = "#{word}"
  else if prefix is 'upper_case'
    func = "#{word}".toUpperCase()
  else
    if word
      end = "#{word[0].toUpperCase()}#{word.slice(1)}"
    else
      end = ''
    func = "#{prefix}#{end}"

styledConsoleLog = ->
  argArray = []
  if arguments.length
    startTagRe = /<span\s+style=(['"])([^'"]*)\1\s*>/gi
    endTagRe = /<\/span>/gi
    reResultArray = undefined
    argArray.push arguments[0].replace(startTagRe, '%c').replace(endTagRe, '%c')
    while reResultArray = startTagRe.exec(arguments[0])
      argArray.push reResultArray[2]
      argArray.push ''
    j = 1
    while j < arguments.length
      argArray.push arguments[j]
      j++
  console.log.apply console, argArray
  return

# ---
# generated by js2coffee 2.0.1

startHacking = =>
  jQuery.fn.hack = () ->
    console.log("%cSearching for Flash Functions...", "color: blue; font-size: x-large");
    console.time("Finding Functions");
    $objects = $(this)
    lists = hack_data.getWords()
    before = hack_data.getPrependWords()
    for el, index in $objects
      console.group "--------------- FLASH ELEMENT #{index} CSS #{cssPath el}---------------"
      for prefix in before
        for word in lists
          func = getFunc(word, prefix)
          if el[func]
            styledConsoleLog '<span style="color:cadetblue"> FLASH FUNCTION:</span><span style="color:green;">' + func + '</span>'
      console.groupEnd()
    console.timeEnd("Finding Functions");
    return
  jQuery('object[type="application/x-shockwave-flash"]').hack()


startHacking()